---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-henriqzimer-tls
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: wildcard-certificate
    app.kubernetes.io/component: tls
    app.kubernetes.io/managed-by: helmfile
    environment: production
spec:
  secretName: wildcard-henriqzimer-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - '*.henriqzimer.com.br'
    - 'henriqzimer.com.br'
  secretTemplate:
    labels:
      app.kubernetes.io/name: wildcard-certificate
      app.kubernetes.io/component: tls
